version: '3.2'

volumes:
  mongodata:

networks:
  docker_demo:
    driver: bridge

services:
  docker_demo_mongodb:
    image: mvertes/alpine-mongo:3.6.5-0
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
    networks:
      - docker_demo

  docker_demo_userservice:
      image: docker_demo_userservice:1.0
      build: ./backend/userService/
      links:
        - docker_demo_mongodb      
      environment:
        PORT: 3000
        MONGO_URL: 'mongodb://docker_demo_mongodb:27017/user_notes'      
      expose:
        - 3000        
      ports:
        - "3000:3000"
      networks:
        - docker_demo

  docker_demo_noteservice:
    image: docker_demo_noteservice:1.0
    build: ./backend/noteService/
    links:
      - docker_demo_mongodb       
    environment:
      PORT: 3001
      MONGO_URL: 'mongodb://docker_demo_mongodb:27017/user_notes'    
    expose:
      - 3001      
    ports:
      - "3001:3001"
    networks:
      - docker_demo

  docker_demo_frontend:
      image: docker_demo_frontend:1.0
      build: ./production_frontend/
      links:
        - docker_demo_mongodb         
      expose:
        - 9000
      ports:
        - "9000:9000"